---
title: "HW 01"
author: "Cat Xia"
format: 
  html:
    embed-resources: true
toc: true
---

## 0 - Setup

```{r setup}
if (!require("pacman")) 
  install.packages("pacman")

# use this line for installing/loading
pacman::p_load(tidyverse, here, glue, scales) 

devtools::install_github("tidyverse/dsbox")
```

## 1 - Road traffic accidents in Edinburgh
```{r Load Data: accidents}
accidents_file_loc <- here("data", "accidents.csv")
accidents <- read.csv(accidents_file_loc)
#accidents |> 
  #glimpse()
```

```{r}
#create column that separates weekdays from weekend. Change time to the hour minute second format
accidents <- accidents |>
  mutate(
    day_of_week_cat = ifelse(day_of_week %in% c("Saturday", "Sunday"), "Weekend", "Weekday"),
    time = hms(time),
    time_sec = as.numeric(time)
  )
    #code from https://stackoverflow.com/questions/28893193/creating-factor-variables-weekend-and-weekday-from-date
```


```{r label-me-1}
accidents |>
  #set x as time in the day, and group as severity
  ggplot(aes(x = time_sec, group = severity, fill = severity)) +
  
  #create a density plot with 50% fill
  geom_density(alpha = 0.5) +
  
  #separate graphs based on weekend or weekday
  facet_wrap(~day_of_week_cat, nrow = 2) +
  
  #labels
  labs(
    x = "Time of day",
    y = "Density",
    color = NULL,
    title = "Number of accidents throughout the day",
    subtitle = "By day of week and severity"
  ) +
  scale_x_continuous(
    labels = function(x) format(seconds_to_period(x))  # convert seconds back to HH:MM:SS
  )+
  theme_minimal()

```

## 2 - NYC marathon winners

```{r label-me-2}

```

## 3 - US counties

## 4 - Rental apartments in SF

## 5 - Napoleon’s march.
